# Generated by Django 6.0.7 on 2026-09-15 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
    ]
