# Generated by Django 6.0.7 on 2026-09-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
