# Generated by Django 6.0.7 on 2026-08-31 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='max_amount',
            new_name='amount_paid',
        ),
    ]
