# Generated by Django 6.0.7 on 2026-09-17 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_order_date_shipped'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Prompt sent'), ('success', 'Successful'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timed out')], db_index=True, default='pending', max_length=16)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_transactions', to='payment.order')),
            ],
            options={
                'verbose_name': 'M-Pesa transaction',
                'verbose_name_plural': 'M-Pesa transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', 'status'], name='payment_mpe_order_i_730277_idx'), models.Index(fields=['status', 'created_at'], name='payment_mpe_status_a97604_idx')],
            },
        ),
    ]
