# Generated by Django 6.0.7 on 2026-09-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_mpesatransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash_on_delivery', 'Cash on Delivery'), ('card', 'Card')], default='mpesa', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
