"""
Django settings for ecom project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-axkmr6+s0_p!05)hdo@!*k262(r^&ii($oh=ei8+&%ghnz*pg^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "sokohub-ct0d.onrender.com",
    "localhost",
    "127.0.0.1",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'cart',
    'payment',
    'cloudinary',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecom.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ["DB_NAME"],
        "USER": os.environ["DB_USER"],
        "PASSWORD": os.environ["DB_PASSWORD"],
        "HOST": os.environ["DB_HOST"],
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}


import os

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.environ.get("CLOUDINARY_CLOUD_NAME"),
    "API_KEY": os.environ.get("CLOUDINARY_API_KEY"),
    "API_SECRET": os.environ.get("CLOUDINARY_API_SECRET"),
}

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")



"""
Reference snippets — copy the relevant parts into your real files.
Nothing here should be imported as-is.
"""

# ===========================================================================
# 1. payments/urls.py
# ===========================================================================
URLS = '''
from django.urls import path

from . import views

urlpatterns = [
    path("mpesa/callback/", views.mpesa_callback, name="mpesa_callback"),
    path(
        "mpesa/status/<str:checkout_request_id>/",
        views.mpesa_status,
        name="mpesa_status",
    ),
]
'''

# In your project urls.py (only if payments isn't already included):
#   path("payments/", include("payments.urls")),


BASE_URLS = {
    "sandbox": "https://sandbox.safaricom.co.ke",
    "production": "https://api.safaricom.co.ke",
}

ACCESS_TOKEN_CACHE_KEY = "mpesa:access_token"
# Daraja tokens live 3599s; refresh a little early.
ACCESS_TOKEN_TTL = 3000

CONSUMER_KEY    = os.getenv("CONSUMER_KEY")
CONSUMER_SECRET = os.getenv("CONSUMER_SECRET")
SHORT_CODE      = os.getenv("SHORT_CODE")
PASSKEY         = os.getenv("PASSKEY")
PHONE_NUMBER    = os.getenv("PHONE_NUMBER")
INITIATOR_NAME  = os.getenv("INITIATOR_NAME")
INITIATOR_PASSWORD = os.getenv("INITIATOR_PASSWORD")
PARTY_A         = os.getenv("PARTY_A")
PARTY_B         = os.getenv("PARTY_B")
C2B_SHORT_CODE = os.getenv("C2B_SHORT_CODE", SHORT_CODE)  # default to SHORT_CODE if not set
C2B_SAFARICOM_SANDBOX_URL = os.getenv("C2B_SAFARICOM_SANDBOX_URL")
SAFARICOM_SANDBOX_TOKEN_URL = os.getenv("SAFARICOM_SANDBOX_TOKEN_URL")
SAFARICOM_SANDBOX_STK_PUSH_URL = os.getenv("SAFARICOM_SANDBOX_STK_PUSH_URL")

# Callback URL must be a publicly reachable URL (e.g. ngrok tunnel).
# Set MPESA_CALLBACK_URL in your .env file — never hardcode it here.
CALLBACK_URL        = os.getenv("CALLBACK_URL")
C2B_VALIDATION_URL  = os.getenv("C2B_VALIDATION_URL")
C2B_CONFIRMATION_URL= os.getenv("C2B_CONFIRMATION_URL")

# ===========================================================================
# 2. settings.py  — environment-driven configuration
# ===========================================================================
SETTINGS = '''
import os

MPESA_ENVIRONMENT = os.environ.get("MPESA_ENVIRONMENT", "sandbox")  # or "production"
MPESA_CONSUMER_KEY = os.environ.get("MPESA_CONSUMER_KEY", "")
MPESA_CONSUMER_SECRET = os.environ.get("MPESA_CONSUMER_SECRET", "")
MPESA_SHORTCODE = os.environ.get("MPESA_SHORTCODE", "")
MPESA_PASSKEY = os.environ.get("MPESA_PASSKEY", "")
MPESA_CALLBACK_URL = os.environ.get("MPESA_CALLBACK_URL", "")

# Optional
MPESA_TRANSACTION_TYPE = os.environ.get(
    "MPESA_TRANSACTION_TYPE", "CustomerPayBillOnline"   # "CustomerBuyGoodsOnline" for Till
)
MPESA_PARTY_B = os.environ.get("MPESA_PARTY_B", MPESA_SHORTCODE)  # Till: store number
MPESA_HTTP_TIMEOUT = int(os.environ.get("MPESA_HTTP_TIMEOUT", "30"))
MPESA_ORDER_MODEL = "orders.Order"        # <-- point at your real Order model
MPESA_CALLBACK_ALLOWED_IPS = None         # True in production to lock to Safaricom IPs

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "loggers": {
        "payments": {"handlers": ["console"], "level": "INFO"},
    },
}
'''


# ===========================================================================
# 3. The checkout view patch  —  replace the "mark it paid" part of process_order
# ===========================================================================
PROCESS_ORDER = '''
# in your existing checkout app views.py

import logging

from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import redirect, render

from payments.forms import MpesaPaymentForm
from payments.mpesa_client import MpesaError
from payments.services import initiate_stk_push, order_total
from payments.views import SESSION_TXN_KEY

logger = logging.getLogger(__name__)


def _wants_json(request):
    return request.headers.get("X-Requested-With") == "XMLHttpRequest"


def process_order(request):
    if request.method != "POST":
        return redirect("cart_summary")

    billing_form = BillingForm(request.POST)          # your existing form
    payment_form = MpesaPaymentForm(request.POST)

    if not (billing_form.is_valid() and payment_form.is_valid()):
        errors = {**billing_form.errors, **payment_form.errors}
        if _wants_json(request):
            return JsonResponse({"ok": False, "errors": errors}, status=400)
        return render(request, "payment/billing_info.html", {
            "billing_form": billing_form,
            "payment_form": payment_form,
            # ... your existing context
        })

    # --- KEEP your existing order-creation code here. -----------------------
    # Create the order + order items in a PENDING / unpaid state exactly as you
    # do now, but DO NOT mark it paid and DO NOT clear the cart yet.
    order = create_order_from_cart(request, billing_form.cleaned_data)   # yours
    # -----------------------------------------------------------------------

    phone = payment_form.cleaned_data["mpesa_phone_number"]
    amount = order_total(order)            # server-side, never from the POST body

    try:
        txn = initiate_stk_push(order, phone, amount)
    except MpesaError as exc:
        if _wants_json(request):
            return JsonResponse({"ok": False, "error": str(exc)}, status=502)
        messages.error(request, str(exc))
        return redirect("checkout")

    # Remember which transactions this browser may poll.
    ids = request.session.get(SESSION_TXN_KEY, [])
    ids.append(txn.checkout_request_id)
    request.session[SESSION_TXN_KEY] = ids[-10:]
    request.session["pending_order_id"] = order.pk

    if _wants_json(request):
        return JsonResponse({
            "ok": True,
            "checkout_request_id": txn.checkout_request_id,
            "phone": txn.masked_phone(),
        })

    # Non-JS fallback: a simple "waiting for payment" page that polls.
    return render(request, "payment/mpesa_waiting.html", {"transaction": txn})
'''


# ===========================================================================
# 4. payments/admin.py (optional but useful for support)
# ===========================================================================
ADMIN = '''
from django.contrib import admin

from .models import MpesaTransaction


@admin.register(MpesaTransaction)
class MpesaTransactionAdmin(admin.ModelAdmin):
    list_display = ("checkout_request_id", "order", "masked_phone", "amount",
                    "status", "mpesa_receipt_number", "created_at")
    list_filter = ("status", "created_at")
    search_fields = ("checkout_request_id", "merchant_request_id",
                     "mpesa_receipt_number", "phone_number")
    readonly_fields = [f.name for f in MpesaTransaction._meta.fields]

    def has_add_permission(self, request):
        return False
'''
